exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
paginate: 2
paginate_path: 'blog/page:num'
jekyll-mentions: 'https://twitter.com'
twitter:
  username: DavidDarnes
author: DavidDarnes
social:
  name: David Darnes
  links:
    - 'https://twitter.com/DavidDarnes'
    - 'https://www.facebook.com/daviddarnes'
    - 'https://www.linkedin.com/in/daviddarnes'
    - 'https://github.com/daviddarnes'
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: |
      Welcome to the blog
    feature_image: 'https://picsum.photos/2560/600?image=866'
defaults:
  - scope:
      path: ''
    values:
      image: /assets/default-social-image.png
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
encoding: utf-8
lang: en-GB
title: Alembic
logo: /assets/logos/logo.svg
description: >-
  Alembic is a starting point for Jekyll projects. Rather than starting from
  scratch, this boilerplate is designed to get the ball rolling immediately
url: ''
baseurl: ''
repo: 'https://github.com/daviddarnes/alembic'
email: me@daviddarnes.com
css_inline: true
favicons:
  '16': /assets/logos/logo@16px.png
  '32': /assets/logos/logo@32px.png
  '96': /assets/logos/logo@96px.png
  '120': /assets/logos/logo@120px.png
  '144': /assets/logos/logo@144px.png
  '180': /assets/logos/logo@180px.png
  '512': /assets/logos/logo@512px.png
  '1024': /assets/logos/logo@1024px.png
navigation_header:
  - title: Home
    url: /
  - title: Elements
    url: /elements/
  - title: Blog
    url: /blog/
  - title: Categories
    url: /categories/
  - title: Search
    url: /search/
  - title: Fork Alembic
    url: 'https://github.com/daviddarnes/alembic'
navigation_footer:
  - title: Created by David Darnes
    url: 'https://darn.es'
social_links:
  Twitter: 'https://twitter.com/DavidDarnes'
  LinkedIn: 'https://www.linkedin.com/in/daviddarnes'
  GitHub: 'https://github.com/daviddarnes'
  link: 'https://darn.es'
  RSS: /feed.xml
sharing_links:
  Twitter: '#0d94e7'
  facebook: '#3B5998'
  Email: true
fonts:
  preconnect_urls:
    - 'https://fonts.gstatic.com'
  font_urls:
    - >-
      https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
